version: '3.8'

services:

  laravel:
    build: .
    container_name: laravel_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer_service
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3309:3306"
